### PR TITLE
chore(package): use array of author objects for contributors

### PR DESCRIPTION
**Pull request by leodido**

### CODE REVIEW

**Comment by paradox41** [comment]
lgtm

**Comment by paradox41** [comment]
@leodido what is your npm username? Can you give me a link to your npm profile?

**Comment by leodido** [comment]
I always use leodido as username.

This is my [npm profile](https://www.npmjs.com/~leodido).

**Comment by paradox41** [comment]
I added you as a collaborator: https://www.npmjs.com/package/validate-commit

I was poking around and realized I had to add you. :D

**Pull request merged**
